services:
  quiz:
    build: .
    restart: always
    container_name: ${PROJECT_NAME}
    env_file:
      - .env
    volumes:
      - ./${DATA_FOLDER}:/app/data
    labels:
      caddy: ${PROJECT_NAME}.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams ${INTERNAL_PORT}}}"
    networks:
      - caddy-proxy-network
      - internal-network

  bot:
    build: .
    restart: always
    command: npm run bot
    environment:
      - WS_URL=ws://quiz:${INTERNAL_PORT}
    depends_on:
      - quiz
    networks:
      - internal-network

networks:
  caddy-proxy-network:
    external: true
  internal-network:
    driver: bridge
